spring.application.name=BookingSystem

spring.datasource.url=jdbc:mysql://localhost:3306/bookingsystem?useSSL=false&serverTimezone=UTC


! Database Username/Password

! Method 1: SAFE! Default - (Runtime Environments)
# Guide (IntelliJ -> Run -> Edit Configurations -> BookingSystemApplication -> Modify Options -> Environments Variables)
# In the now newly appeared box write -- DB_USER=username_Here;DB_PASS=password_Here --  Then click Apply

! Method 2: NOT RECOMMENDED!!! Direct input, Sensitive data can be pushed!
# Switch out ${DB_PASS} & ${DB_USER} with your username & password
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true